### ISSUE TITLE
The visualisation button on the left menu is enabled even when no sphere is selected.

### ISSUE THREAD

**Issue by nick-stebbings** [HabFract/monorepo#15]
This could either trigger a modal, asking which sphere to select, or we could gray it out with a tooltip (when the currentSphere atom is not returning a value),  the tooltip stating the user needs to select a sphere from the menu.

I can see either of these solutions working but perhaps the latter is a bit more straightforward.

**Comment by NickWhiu** [comment]
Depends on #7 first

**Comment by nick-stebbings** [comment]
The more I think about it, the more I think refactoring the expanded menu will be the solution to this problem.
The story/flow could be:

- As a user (:P) I want to visualise a sphere
- I click the visualise button despite not having selected a sphere
- Since there is no context for the visualisation, the menu expands and a tooltip asks me to pick a sphere from the menu
- Once that has been done, the vis is displayed and the menu collapses again

Thoughts? @NickWhiu
